import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[70%] mx-auto sticky top-0 z-50 bg-white">
          <NavBar />
        </div>
        <div className="w-full max-w-7xl px-4 mx-auto">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
